DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'laravel') THEN
CREATE ROLE laravel WITH LOGIN ENCRYPTED PASSWORD 'secret';
END IF;
END
$$;

GRANT ALL PRIVILEGES ON DATABASE pizza_app_db TO laravel;

\connect pizza_app_db

GRANT USAGE ON SCHEMA public TO laravel;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO laravel;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO laravel;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO laravel;
